version: "2"

services:
  mrbs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mrbs
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=mrbs-db
      - DB_USER=mrbs-user
      - DB_PASS=mrbs-pass
      - DB_DATABASE=mrbs
    volumes:
      - mrbs_vol:/config
      # - ./dev/modern-mrbs-theme/modern:/app/www/public/Themes/modern
    ports:
      - "8888:80"
    depends_on:
      - mrbs-db
    networks:
      - mrbs-net

  mrbs-db:
    image: docker.io/mariadb:latest
    container_name: mrbs-db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mrbs-root-pass
      - TZ=Europe/London
      - MYSQL_DATABASE=mrbs
      - MYSQL_USER=mrbs-user
      - MYSQL_PASSWORD=mrbs-pass
    volumes:
      - mrbs_db_vol:/var/lib/mysql
    networks:
      - mrbs-net

volumes:
  mrbs_vol: {}
  mrbs_db_vol: {}

networks:
  mrbs-net:
    driver: bridge
